### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by blackslate** [lexogram/parallax#1]
## Features

- [ ] 1. Prevent inertial scrolling
- [ ] 2. Control scrollWidth on all platforms and browsers
- [ ] 3. Determined drag to change section
- [ ] 4. Multilingual text and audio
- [ ] 5. Behaviours

## Future features
- [ ] A. Second-level perspective (ex: inside | outside train )
- [ ] B. Scroll vertically to move in and out
- [ ] C. Choice of forking path
- [ ] D. Collection of objects (visible or hidden), which control paths available
- [ ] E. Myst-like: toggle switches to change display elsewhere in same section or in other sections.
